/**
 * generated by Xtext 2.17.0
 */
package blatt2.ui;

import blatt2.ui.AbstractBlatt2UiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class Blatt2UiModule extends AbstractBlatt2UiModule {
  public Blatt2UiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
