/**
 * generated by Xtext 2.17.0
 */
package blatt2.scoping;

import blatt2.scoping.AbstractBlatt2ScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class Blatt2ScopeProvider extends AbstractBlatt2ScopeProvider {
}
