/**
 * generated by Xtext 2.18.0.M3
 */
package org.xtext.example.mydsl.myDsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.util.EObjectResolvingEList;

import org.xtext.example.mydsl.myDsl.Link;
import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.SystemEnvironment;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>System Environment</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.SystemEnvironmentImpl#getContainer <em>Container</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.SystemEnvironmentImpl#getLink <em>Link</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SystemEnvironmentImpl extends AbstractElementImpl implements SystemEnvironment
{
  /**
   * The cached value of the '{@link #getContainer() <em>Container</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getContainer()
   * @generated
   * @ordered
   */
  protected EList<org.xtext.example.mydsl.myDsl.Container> container;

  /**
   * The cached value of the '{@link #getLink() <em>Link</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLink()
   * @generated
   * @ordered
   */
  protected EList<Link> link;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SystemEnvironmentImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.SYSTEM_ENVIRONMENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<org.xtext.example.mydsl.myDsl.Container> getContainer()
  {
    if (container == null)
    {
      container = new EObjectResolvingEList<org.xtext.example.mydsl.myDsl.Container>(org.xtext.example.mydsl.myDsl.Container.class, this, MyDslPackage.SYSTEM_ENVIRONMENT__CONTAINER);
    }
    return container;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Link> getLink()
  {
    if (link == null)
    {
      link = new EObjectResolvingEList<Link>(Link.class, this, MyDslPackage.SYSTEM_ENVIRONMENT__LINK);
    }
    return link;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.SYSTEM_ENVIRONMENT__CONTAINER:
        return getContainer();
      case MyDslPackage.SYSTEM_ENVIRONMENT__LINK:
        return getLink();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.SYSTEM_ENVIRONMENT__CONTAINER:
        getContainer().clear();
        getContainer().addAll((Collection<? extends org.xtext.example.mydsl.myDsl.Container>)newValue);
        return;
      case MyDslPackage.SYSTEM_ENVIRONMENT__LINK:
        getLink().clear();
        getLink().addAll((Collection<? extends Link>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.SYSTEM_ENVIRONMENT__CONTAINER:
        getContainer().clear();
        return;
      case MyDslPackage.SYSTEM_ENVIRONMENT__LINK:
        getLink().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.SYSTEM_ENVIRONMENT__CONTAINER:
        return container != null && !container.isEmpty();
      case MyDslPackage.SYSTEM_ENVIRONMENT__LINK:
        return link != null && !link.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //SystemEnvironmentImpl
