/*
 * generated by Xtext 2.17.1
 */
package blatt2.parser.antlr;

import blatt2.parser.antlr.internal.InternalBlatt2Parser;
import blatt2.services.Blatt2GrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class Blatt2Parser extends AbstractAntlrParser {

	@Inject
	private Blatt2GrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalBlatt2Parser createParser(XtextTokenStream stream) {
		return new InternalBlatt2Parser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "AllocationContext";
	}

	public Blatt2GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(Blatt2GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
