/**
 * generated by Xtext 2.17.0
 */
package blatt2.tests;

import blatt2.tests.Blatt2InjectorProvider;
import com.google.inject.Inject;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

@ExtendWith(InjectionExtension.class)
@InjectWith(Blatt2InjectorProvider.class)
@SuppressWarnings("all")
public class Blatt2ParsingTest {
  @Inject
  private /* ParseHelper<AllocationContext> */Object parseHelper;
  
  @Test
  public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field Blatt2ParsingTest.parseHelper refers to the missing type AllocationContext"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nisEmpty cannot be resolved"
      + "\njoin cannot be resolved");
  }
}
