/**
 * generated by Xtext 2.17.0
 */
package blatt2.validation;

import blatt2.validation.AbstractBlatt2Validator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class Blatt2Validator extends AbstractBlatt2Validator {
}
