/**
 * generated by Xtext 2.17.0
 */
package blatt2;

import blatt2.Blatt2StandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class Blatt2StandaloneSetup extends Blatt2StandaloneSetupGenerated {
  public static void doSetup() {
    new Blatt2StandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
