/**
 * generated by Xtext 2.17.0
 */
package blatt2;

import blatt2.AbstractBlatt2RuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class Blatt2RuntimeModule extends AbstractBlatt2RuntimeModule {
}
