/**
 * generated by Xtext 2.18.0.M3
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Container</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Container#getLinks <em>Links</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getContainer()
 * @model
 * @generated
 */
public interface Container extends AbstractElement
{
  /**
   * Returns the value of the '<em><b>Links</b></em>' reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Link}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Links</em>' reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getContainer_Links()
   * @model
   * @generated
   */
  EList<Link> getLinks();

} // Container
