/**
 * generated by Xtext 2.18.0.M3
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Long</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getLong()
 * @model
 * @generated
 */
public interface Long extends Type
{
} // Long
