/**
 * generated by Xtext 2.18.0.M3
 */
package org.xtext.example.mydsl.myDsl;

import java.lang.String;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.myDsl.MyDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/MyDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslPackage eINSTANCE = org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ModelImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Greetings</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__GREETINGS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.AbstractElementImpl <em>Abstract Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.AbstractElementImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getAbstractElement()
   * @generated
   */
  int ABSTRACT_ELEMENT = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_ELEMENT__NAME = 0;

  /**
   * The number of structural features of the '<em>Abstract Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_ELEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.AllocationContextImpl <em>Allocation Context</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.AllocationContextImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getAllocationContext()
   * @generated
   */
  int ALLOCATION_CONTEXT = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALLOCATION_CONTEXT__NAME = ABSTRACT_ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Allocated Assembly Context</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALLOCATION_CONTEXT__ALLOCATED_ASSEMBLY_CONTEXT = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Target Container</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALLOCATION_CONTEXT__TARGET_CONTAINER = ABSTRACT_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Allocation Context</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALLOCATION_CONTEXT_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.SystemEnvironmentImpl <em>System Environment</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.SystemEnvironmentImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getSystemEnvironment()
   * @generated
   */
  int SYSTEM_ENVIRONMENT = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_ENVIRONMENT__NAME = ABSTRACT_ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Container</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_ENVIRONMENT__CONTAINER = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Link</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_ENVIRONMENT__LINK = ABSTRACT_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>System Environment</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_ENVIRONMENT_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ComponentImpl <em>Component</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ComponentImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getComponent()
   * @generated
   */
  int COMPONENT = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT__NAME = ABSTRACT_ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Required Interface</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT__REQUIRED_INTERFACE = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Required Service</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT__REQUIRED_SERVICE = ABSTRACT_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Provided Interface</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT__PROVIDED_INTERFACE = ABSTRACT_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Provided Service</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT__PROVIDED_SERVICE = ABSTRACT_ELEMENT_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Behaviour Description</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT__BEHAVIOUR_DESCRIPTION = ABSTRACT_ELEMENT_FEATURE_COUNT + 4;

  /**
   * The feature id for the '<em><b>Encapsulated Assembly Context</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT__ENCAPSULATED_ASSEMBLY_CONTEXT = ABSTRACT_ELEMENT_FEATURE_COUNT + 5;

  /**
   * The number of structural features of the '<em>Component</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 6;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ContainerImpl <em>Container</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ContainerImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getContainer()
   * @generated
   */
  int CONTAINER = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTAINER__NAME = ABSTRACT_ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Links</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTAINER__LINKS = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Container</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTAINER_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.SystemImpl <em>System</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.SystemImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getSystem()
   * @generated
   */
  int SYSTEM = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM__NAME = ABSTRACT_ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Encapsulated Assembly Context</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM__ENCAPSULATED_ASSEMBLY_CONTEXT = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Allocation Context</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM__ALLOCATION_CONTEXT = ABSTRACT_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Provided Interfaces</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM__PROVIDED_INTERFACES = ABSTRACT_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Environment</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM__ENVIRONMENT = ABSTRACT_ELEMENT_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>System</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.AssemblyContextImpl <em>Assembly Context</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.AssemblyContextImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getAssemblyContext()
   * @generated
   */
  int ASSEMBLY_CONTEXT = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSEMBLY_CONTEXT__NAME = ABSTRACT_ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Required Role</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSEMBLY_CONTEXT__REQUIRED_ROLE = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Allocation Context</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSEMBLY_CONTEXT__ALLOCATION_CONTEXT = ABSTRACT_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Provided Role</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSEMBLY_CONTEXT__PROVIDED_ROLE = ABSTRACT_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Component</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSEMBLY_CONTEXT__COMPONENT = ABSTRACT_ELEMENT_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Assembly Context</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSEMBLY_CONTEXT_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.LinkImpl <em>Link</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.LinkImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getLink()
   * @generated
   */
  int LINK = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINK__NAME = ABSTRACT_ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Linked Containers</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINK__LINKED_CONTAINERS = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Link</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINK_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.RoleImpl <em>Role</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.RoleImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getRole()
   * @generated
   */
  int ROLE = 9;

  /**
   * The number of structural features of the '<em>Role</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROLE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.BehaviorDescriptionImpl <em>Behavior Description</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.BehaviorDescriptionImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getBehaviorDescription()
   * @generated
   */
  int BEHAVIOR_DESCRIPTION = 10;

  /**
   * The feature id for the '<em><b>Called Services</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BEHAVIOR_DESCRIPTION__CALLED_SERVICES = 0;

  /**
   * The feature id for the '<em><b>Internal Actions</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BEHAVIOR_DESCRIPTION__INTERNAL_ACTIONS = 1;

  /**
   * The feature id for the '<em><b>Loops</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BEHAVIOR_DESCRIPTION__LOOPS = 2;

  /**
   * The feature id for the '<em><b>Branches</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BEHAVIOR_DESCRIPTION__BRANCHES = 3;

  /**
   * The number of structural features of the '<em>Behavior Description</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BEHAVIOR_DESCRIPTION_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ServiceImpl <em>Service</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ServiceImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getService()
   * @generated
   */
  int SERVICE = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVICE__NAME = ABSTRACT_ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Corresponding Signature</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVICE__CORRESPONDING_SIGNATURE = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Service</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVICE_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.InterfaceImpl <em>Interface</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.InterfaceImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getInterface()
   * @generated
   */
  int INTERFACE = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERFACE__NAME = ABSTRACT_ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Signature</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERFACE__SIGNATURE = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Interface</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERFACE_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.SignatureImpl <em>Signature</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.SignatureImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getSignature()
   * @generated
   */
  int SIGNATURE = 13;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIGNATURE__NAME = ABSTRACT_ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Return Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIGNATURE__RETURN_TYPE = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Parameter Type</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIGNATURE__PARAMETER_TYPE = ABSTRACT_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Signature</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIGNATURE_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.DelegationConnectorImpl <em>Delegation Connector</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.DelegationConnectorImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getDelegationConnector()
   * @generated
   */
  int DELEGATION_CONNECTOR = 14;

  /**
   * The feature id for the '<em><b>Role</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DELEGATION_CONNECTOR__ROLE = 0;

  /**
   * The feature id for the '<em><b>Interface</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DELEGATION_CONNECTOR__INTERFACE = 1;

  /**
   * The number of structural features of the '<em>Delegation Connector</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DELEGATION_CONNECTOR_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.InternalActionImpl <em>Internal Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.InternalActionImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getInternalAction()
   * @generated
   */
  int INTERNAL_ACTION = 15;

  /**
   * The number of structural features of the '<em>Internal Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERNAL_ACTION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.LoopImpl <em>Loop</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.LoopImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getLoop()
   * @generated
   */
  int LOOP = 16;

  /**
   * The number of structural features of the '<em>Loop</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOP_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.BranchImpl <em>Branch</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.BranchImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getBranch()
   * @generated
   */
  int BRANCH = 17;

  /**
   * The number of structural features of the '<em>Branch</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BRANCH_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.TypeImpl <em>Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.TypeImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getType()
   * @generated
   */
  int TYPE = 18;

  /**
   * The number of structural features of the '<em>Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ListImpl <em>List</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ListImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getList()
   * @generated
   */
  int LIST = 19;

  /**
   * The number of structural features of the '<em>List</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST_FEATURE_COUNT = TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.MapImpl <em>Map</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.MapImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getMap()
   * @generated
   */
  int MAP = 20;

  /**
   * The number of structural features of the '<em>Map</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAP_FEATURE_COUNT = TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ComplexTypeImpl <em>Complex Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ComplexTypeImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getComplexType()
   * @generated
   */
  int COMPLEX_TYPE = 21;

  /**
   * The number of structural features of the '<em>Complex Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPLEX_TYPE_FEATURE_COUNT = TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.DateImpl <em>Date</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.DateImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getDate()
   * @generated
   */
  int DATE = 22;

  /**
   * The number of structural features of the '<em>Date</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATE_FEATURE_COUNT = TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.DoubleImpl <em>Double</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.DoubleImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getDouble()
   * @generated
   */
  int DOUBLE = 23;

  /**
   * The number of structural features of the '<em>Double</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOUBLE_FEATURE_COUNT = TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.String0Impl <em>String0</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.String0Impl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getString0()
   * @generated
   */
  int STRING0 = 24;

  /**
   * The number of structural features of the '<em>String0</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING0_FEATURE_COUNT = TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.Int0Impl <em>Int0</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.Int0Impl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getInt0()
   * @generated
   */
  int INT0 = 25;

  /**
   * The number of structural features of the '<em>Int0</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT0_FEATURE_COUNT = TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.CharImpl <em>Char</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.CharImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getChar()
   * @generated
   */
  int CHAR = 26;

  /**
   * The number of structural features of the '<em>Char</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHAR_FEATURE_COUNT = TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.LongImpl <em>Long</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.LongImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getLong()
   * @generated
   */
  int LONG = 27;

  /**
   * The number of structural features of the '<em>Long</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LONG_FEATURE_COUNT = TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.FloatImpl <em>Float</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.FloatImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getFloat()
   * @generated
   */
  int FLOAT = 28;

  /**
   * The number of structural features of the '<em>Float</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLOAT_FEATURE_COUNT = TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.BooleanImpl <em>Boolean</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.BooleanImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getBoolean()
   * @generated
   */
  int BOOLEAN = 29;

  /**
   * The number of structural features of the '<em>Boolean</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN_FEATURE_COUNT = TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.VoidImpl <em>Void</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.VoidImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getVoid()
   * @generated
   */
  int VOID = 30;

  /**
   * The number of structural features of the '<em>Void</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VOID_FEATURE_COUNT = TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.StringImpl <em>String</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.StringImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getString()
   * @generated
   */
  int STRING = 31;

  /**
   * The number of structural features of the '<em>String</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_FEATURE_COUNT = STRING0_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.IntImpl <em>Int</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.IntImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getInt()
   * @generated
   */
  int INT = 32;

  /**
   * The number of structural features of the '<em>Int</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_FEATURE_COUNT = INT0_FEATURE_COUNT + 0;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.example.mydsl.myDsl.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Model#getGreetings <em>Greetings</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Greetings</em>'.
   * @see org.xtext.example.mydsl.myDsl.Model#getGreetings()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Greetings();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.AbstractElement <em>Abstract Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Abstract Element</em>'.
   * @see org.xtext.example.mydsl.myDsl.AbstractElement
   * @generated
   */
  EClass getAbstractElement();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.AbstractElement#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.AbstractElement#getName()
   * @see #getAbstractElement()
   * @generated
   */
  EAttribute getAbstractElement_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.AllocationContext <em>Allocation Context</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Allocation Context</em>'.
   * @see org.xtext.example.mydsl.myDsl.AllocationContext
   * @generated
   */
  EClass getAllocationContext();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.example.mydsl.myDsl.AllocationContext#getAllocatedAssemblyContext <em>Allocated Assembly Context</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Allocated Assembly Context</em>'.
   * @see org.xtext.example.mydsl.myDsl.AllocationContext#getAllocatedAssemblyContext()
   * @see #getAllocationContext()
   * @generated
   */
  EReference getAllocationContext_AllocatedAssemblyContext();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.example.mydsl.myDsl.AllocationContext#getTargetContainer <em>Target Container</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Target Container</em>'.
   * @see org.xtext.example.mydsl.myDsl.AllocationContext#getTargetContainer()
   * @see #getAllocationContext()
   * @generated
   */
  EReference getAllocationContext_TargetContainer();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.SystemEnvironment <em>System Environment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>System Environment</em>'.
   * @see org.xtext.example.mydsl.myDsl.SystemEnvironment
   * @generated
   */
  EClass getSystemEnvironment();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.example.mydsl.myDsl.SystemEnvironment#getContainer <em>Container</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Container</em>'.
   * @see org.xtext.example.mydsl.myDsl.SystemEnvironment#getContainer()
   * @see #getSystemEnvironment()
   * @generated
   */
  EReference getSystemEnvironment_Container();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.example.mydsl.myDsl.SystemEnvironment#getLink <em>Link</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Link</em>'.
   * @see org.xtext.example.mydsl.myDsl.SystemEnvironment#getLink()
   * @see #getSystemEnvironment()
   * @generated
   */
  EReference getSystemEnvironment_Link();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Component <em>Component</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Component</em>'.
   * @see org.xtext.example.mydsl.myDsl.Component
   * @generated
   */
  EClass getComponent();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.example.mydsl.myDsl.Component#getRequiredInterface <em>Required Interface</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Required Interface</em>'.
   * @see org.xtext.example.mydsl.myDsl.Component#getRequiredInterface()
   * @see #getComponent()
   * @generated
   */
  EReference getComponent_RequiredInterface();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.example.mydsl.myDsl.Component#getRequiredService <em>Required Service</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Required Service</em>'.
   * @see org.xtext.example.mydsl.myDsl.Component#getRequiredService()
   * @see #getComponent()
   * @generated
   */
  EReference getComponent_RequiredService();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.example.mydsl.myDsl.Component#getProvidedInterface <em>Provided Interface</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Provided Interface</em>'.
   * @see org.xtext.example.mydsl.myDsl.Component#getProvidedInterface()
   * @see #getComponent()
   * @generated
   */
  EReference getComponent_ProvidedInterface();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.example.mydsl.myDsl.Component#getProvidedService <em>Provided Service</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Provided Service</em>'.
   * @see org.xtext.example.mydsl.myDsl.Component#getProvidedService()
   * @see #getComponent()
   * @generated
   */
  EReference getComponent_ProvidedService();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Component#getBehaviourDescription <em>Behaviour Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Behaviour Description</em>'.
   * @see org.xtext.example.mydsl.myDsl.Component#getBehaviourDescription()
   * @see #getComponent()
   * @generated
   */
  EReference getComponent_BehaviourDescription();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Component#getEncapsulatedAssemblyContext <em>Encapsulated Assembly Context</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Encapsulated Assembly Context</em>'.
   * @see org.xtext.example.mydsl.myDsl.Component#getEncapsulatedAssemblyContext()
   * @see #getComponent()
   * @generated
   */
  EReference getComponent_EncapsulatedAssemblyContext();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Container <em>Container</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Container</em>'.
   * @see org.xtext.example.mydsl.myDsl.Container
   * @generated
   */
  EClass getContainer();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.example.mydsl.myDsl.Container#getLinks <em>Links</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Links</em>'.
   * @see org.xtext.example.mydsl.myDsl.Container#getLinks()
   * @see #getContainer()
   * @generated
   */
  EReference getContainer_Links();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.System <em>System</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>System</em>'.
   * @see org.xtext.example.mydsl.myDsl.System
   * @generated
   */
  EClass getSystem();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.example.mydsl.myDsl.System#getEncapsulatedAssemblyContext <em>Encapsulated Assembly Context</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Encapsulated Assembly Context</em>'.
   * @see org.xtext.example.mydsl.myDsl.System#getEncapsulatedAssemblyContext()
   * @see #getSystem()
   * @generated
   */
  EReference getSystem_EncapsulatedAssemblyContext();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.myDsl.System#getAllocationContext <em>Allocation Context</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Allocation Context</em>'.
   * @see org.xtext.example.mydsl.myDsl.System#getAllocationContext()
   * @see #getSystem()
   * @generated
   */
  EReference getSystem_AllocationContext();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.example.mydsl.myDsl.System#getProvidedInterfaces <em>Provided Interfaces</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Provided Interfaces</em>'.
   * @see org.xtext.example.mydsl.myDsl.System#getProvidedInterfaces()
   * @see #getSystem()
   * @generated
   */
  EReference getSystem_ProvidedInterfaces();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.myDsl.System#getEnvironment <em>Environment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Environment</em>'.
   * @see org.xtext.example.mydsl.myDsl.System#getEnvironment()
   * @see #getSystem()
   * @generated
   */
  EReference getSystem_Environment();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.AssemblyContext <em>Assembly Context</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Assembly Context</em>'.
   * @see org.xtext.example.mydsl.myDsl.AssemblyContext
   * @generated
   */
  EClass getAssemblyContext();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.example.mydsl.myDsl.AssemblyContext#getRequiredRole <em>Required Role</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Required Role</em>'.
   * @see org.xtext.example.mydsl.myDsl.AssemblyContext#getRequiredRole()
   * @see #getAssemblyContext()
   * @generated
   */
  EReference getAssemblyContext_RequiredRole();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.myDsl.AssemblyContext#getAllocationContext <em>Allocation Context</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Allocation Context</em>'.
   * @see org.xtext.example.mydsl.myDsl.AssemblyContext#getAllocationContext()
   * @see #getAssemblyContext()
   * @generated
   */
  EReference getAssemblyContext_AllocationContext();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.example.mydsl.myDsl.AssemblyContext#getProvidedRole <em>Provided Role</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Provided Role</em>'.
   * @see org.xtext.example.mydsl.myDsl.AssemblyContext#getProvidedRole()
   * @see #getAssemblyContext()
   * @generated
   */
  EReference getAssemblyContext_ProvidedRole();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.example.mydsl.myDsl.AssemblyContext#getComponent <em>Component</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Component</em>'.
   * @see org.xtext.example.mydsl.myDsl.AssemblyContext#getComponent()
   * @see #getAssemblyContext()
   * @generated
   */
  EReference getAssemblyContext_Component();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Link <em>Link</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Link</em>'.
   * @see org.xtext.example.mydsl.myDsl.Link
   * @generated
   */
  EClass getLink();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.example.mydsl.myDsl.Link#getLinkedContainers <em>Linked Containers</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Linked Containers</em>'.
   * @see org.xtext.example.mydsl.myDsl.Link#getLinkedContainers()
   * @see #getLink()
   * @generated
   */
  EReference getLink_LinkedContainers();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Role <em>Role</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Role</em>'.
   * @see org.xtext.example.mydsl.myDsl.Role
   * @generated
   */
  EClass getRole();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.BehaviorDescription <em>Behavior Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Behavior Description</em>'.
   * @see org.xtext.example.mydsl.myDsl.BehaviorDescription
   * @generated
   */
  EClass getBehaviorDescription();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.example.mydsl.myDsl.BehaviorDescription#getCalledServices <em>Called Services</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Called Services</em>'.
   * @see org.xtext.example.mydsl.myDsl.BehaviorDescription#getCalledServices()
   * @see #getBehaviorDescription()
   * @generated
   */
  EReference getBehaviorDescription_CalledServices();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.BehaviorDescription#getInternalActions <em>Internal Actions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Internal Actions</em>'.
   * @see org.xtext.example.mydsl.myDsl.BehaviorDescription#getInternalActions()
   * @see #getBehaviorDescription()
   * @generated
   */
  EReference getBehaviorDescription_InternalActions();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.BehaviorDescription#getLoops <em>Loops</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Loops</em>'.
   * @see org.xtext.example.mydsl.myDsl.BehaviorDescription#getLoops()
   * @see #getBehaviorDescription()
   * @generated
   */
  EReference getBehaviorDescription_Loops();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.BehaviorDescription#getBranches <em>Branches</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Branches</em>'.
   * @see org.xtext.example.mydsl.myDsl.BehaviorDescription#getBranches()
   * @see #getBehaviorDescription()
   * @generated
   */
  EReference getBehaviorDescription_Branches();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Service <em>Service</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Service</em>'.
   * @see org.xtext.example.mydsl.myDsl.Service
   * @generated
   */
  EClass getService();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.example.mydsl.myDsl.Service#getCorrespondingSignature <em>Corresponding Signature</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Corresponding Signature</em>'.
   * @see org.xtext.example.mydsl.myDsl.Service#getCorrespondingSignature()
   * @see #getService()
   * @generated
   */
  EReference getService_CorrespondingSignature();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Interface <em>Interface</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Interface</em>'.
   * @see org.xtext.example.mydsl.myDsl.Interface
   * @generated
   */
  EClass getInterface();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.example.mydsl.myDsl.Interface#getSignature <em>Signature</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Signature</em>'.
   * @see org.xtext.example.mydsl.myDsl.Interface#getSignature()
   * @see #getInterface()
   * @generated
   */
  EReference getInterface_Signature();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Signature <em>Signature</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Signature</em>'.
   * @see org.xtext.example.mydsl.myDsl.Signature
   * @generated
   */
  EClass getSignature();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Signature#getReturnType <em>Return Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Return Type</em>'.
   * @see org.xtext.example.mydsl.myDsl.Signature#getReturnType()
   * @see #getSignature()
   * @generated
   */
  EReference getSignature_ReturnType();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.example.mydsl.myDsl.Signature#getParameterType <em>Parameter Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Parameter Type</em>'.
   * @see org.xtext.example.mydsl.myDsl.Signature#getParameterType()
   * @see #getSignature()
   * @generated
   */
  EReference getSignature_ParameterType();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.DelegationConnector <em>Delegation Connector</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Delegation Connector</em>'.
   * @see org.xtext.example.mydsl.myDsl.DelegationConnector
   * @generated
   */
  EClass getDelegationConnector();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.myDsl.DelegationConnector#getRole <em>Role</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Role</em>'.
   * @see org.xtext.example.mydsl.myDsl.DelegationConnector#getRole()
   * @see #getDelegationConnector()
   * @generated
   */
  EReference getDelegationConnector_Role();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.myDsl.DelegationConnector#getInterface <em>Interface</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Interface</em>'.
   * @see org.xtext.example.mydsl.myDsl.DelegationConnector#getInterface()
   * @see #getDelegationConnector()
   * @generated
   */
  EReference getDelegationConnector_Interface();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.InternalAction <em>Internal Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Internal Action</em>'.
   * @see org.xtext.example.mydsl.myDsl.InternalAction
   * @generated
   */
  EClass getInternalAction();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Loop <em>Loop</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Loop</em>'.
   * @see org.xtext.example.mydsl.myDsl.Loop
   * @generated
   */
  EClass getLoop();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Branch <em>Branch</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Branch</em>'.
   * @see org.xtext.example.mydsl.myDsl.Branch
   * @generated
   */
  EClass getBranch();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Type <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Type</em>'.
   * @see org.xtext.example.mydsl.myDsl.Type
   * @generated
   */
  EClass getType();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.List <em>List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>List</em>'.
   * @see org.xtext.example.mydsl.myDsl.List
   * @generated
   */
  EClass getList();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Map <em>Map</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Map</em>'.
   * @see org.xtext.example.mydsl.myDsl.Map
   * @generated
   */
  EClass getMap();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.ComplexType <em>Complex Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Complex Type</em>'.
   * @see org.xtext.example.mydsl.myDsl.ComplexType
   * @generated
   */
  EClass getComplexType();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Date <em>Date</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Date</em>'.
   * @see org.xtext.example.mydsl.myDsl.Date
   * @generated
   */
  EClass getDate();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Double <em>Double</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Double</em>'.
   * @see org.xtext.example.mydsl.myDsl.Double
   * @generated
   */
  EClass getDouble();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.String0 <em>String0</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>String0</em>'.
   * @see org.xtext.example.mydsl.myDsl.String0
   * @generated
   */
  EClass getString0();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Int0 <em>Int0</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Int0</em>'.
   * @see org.xtext.example.mydsl.myDsl.Int0
   * @generated
   */
  EClass getInt0();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Char <em>Char</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Char</em>'.
   * @see org.xtext.example.mydsl.myDsl.Char
   * @generated
   */
  EClass getChar();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Long <em>Long</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Long</em>'.
   * @see org.xtext.example.mydsl.myDsl.Long
   * @generated
   */
  EClass getLong();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Float <em>Float</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Float</em>'.
   * @see org.xtext.example.mydsl.myDsl.Float
   * @generated
   */
  EClass getFloat();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Boolean <em>Boolean</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Boolean</em>'.
   * @see org.xtext.example.mydsl.myDsl.Boolean
   * @generated
   */
  EClass getBoolean();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Void <em>Void</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Void</em>'.
   * @see org.xtext.example.mydsl.myDsl.Void
   * @generated
   */
  EClass getVoid();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.String <em>String</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>String</em>'.
   * @see org.xtext.example.mydsl.myDsl.String
   * @generated
   */
  EClass getString();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Int <em>Int</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Int</em>'.
   * @see org.xtext.example.mydsl.myDsl.Int
   * @generated
   */
  EClass getInt();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDslFactory getMyDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ModelImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Greetings</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__GREETINGS = eINSTANCE.getModel_Greetings();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.AbstractElementImpl <em>Abstract Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.AbstractElementImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getAbstractElement()
     * @generated
     */
    EClass ABSTRACT_ELEMENT = eINSTANCE.getAbstractElement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ABSTRACT_ELEMENT__NAME = eINSTANCE.getAbstractElement_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.AllocationContextImpl <em>Allocation Context</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.AllocationContextImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getAllocationContext()
     * @generated
     */
    EClass ALLOCATION_CONTEXT = eINSTANCE.getAllocationContext();

    /**
     * The meta object literal for the '<em><b>Allocated Assembly Context</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ALLOCATION_CONTEXT__ALLOCATED_ASSEMBLY_CONTEXT = eINSTANCE.getAllocationContext_AllocatedAssemblyContext();

    /**
     * The meta object literal for the '<em><b>Target Container</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ALLOCATION_CONTEXT__TARGET_CONTAINER = eINSTANCE.getAllocationContext_TargetContainer();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.SystemEnvironmentImpl <em>System Environment</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.SystemEnvironmentImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getSystemEnvironment()
     * @generated
     */
    EClass SYSTEM_ENVIRONMENT = eINSTANCE.getSystemEnvironment();

    /**
     * The meta object literal for the '<em><b>Container</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SYSTEM_ENVIRONMENT__CONTAINER = eINSTANCE.getSystemEnvironment_Container();

    /**
     * The meta object literal for the '<em><b>Link</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SYSTEM_ENVIRONMENT__LINK = eINSTANCE.getSystemEnvironment_Link();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ComponentImpl <em>Component</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ComponentImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getComponent()
     * @generated
     */
    EClass COMPONENT = eINSTANCE.getComponent();

    /**
     * The meta object literal for the '<em><b>Required Interface</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPONENT__REQUIRED_INTERFACE = eINSTANCE.getComponent_RequiredInterface();

    /**
     * The meta object literal for the '<em><b>Required Service</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPONENT__REQUIRED_SERVICE = eINSTANCE.getComponent_RequiredService();

    /**
     * The meta object literal for the '<em><b>Provided Interface</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPONENT__PROVIDED_INTERFACE = eINSTANCE.getComponent_ProvidedInterface();

    /**
     * The meta object literal for the '<em><b>Provided Service</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPONENT__PROVIDED_SERVICE = eINSTANCE.getComponent_ProvidedService();

    /**
     * The meta object literal for the '<em><b>Behaviour Description</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPONENT__BEHAVIOUR_DESCRIPTION = eINSTANCE.getComponent_BehaviourDescription();

    /**
     * The meta object literal for the '<em><b>Encapsulated Assembly Context</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPONENT__ENCAPSULATED_ASSEMBLY_CONTEXT = eINSTANCE.getComponent_EncapsulatedAssemblyContext();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ContainerImpl <em>Container</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ContainerImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getContainer()
     * @generated
     */
    EClass CONTAINER = eINSTANCE.getContainer();

    /**
     * The meta object literal for the '<em><b>Links</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTAINER__LINKS = eINSTANCE.getContainer_Links();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.SystemImpl <em>System</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.SystemImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getSystem()
     * @generated
     */
    EClass SYSTEM = eINSTANCE.getSystem();

    /**
     * The meta object literal for the '<em><b>Encapsulated Assembly Context</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SYSTEM__ENCAPSULATED_ASSEMBLY_CONTEXT = eINSTANCE.getSystem_EncapsulatedAssemblyContext();

    /**
     * The meta object literal for the '<em><b>Allocation Context</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SYSTEM__ALLOCATION_CONTEXT = eINSTANCE.getSystem_AllocationContext();

    /**
     * The meta object literal for the '<em><b>Provided Interfaces</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SYSTEM__PROVIDED_INTERFACES = eINSTANCE.getSystem_ProvidedInterfaces();

    /**
     * The meta object literal for the '<em><b>Environment</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SYSTEM__ENVIRONMENT = eINSTANCE.getSystem_Environment();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.AssemblyContextImpl <em>Assembly Context</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.AssemblyContextImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getAssemblyContext()
     * @generated
     */
    EClass ASSEMBLY_CONTEXT = eINSTANCE.getAssemblyContext();

    /**
     * The meta object literal for the '<em><b>Required Role</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASSEMBLY_CONTEXT__REQUIRED_ROLE = eINSTANCE.getAssemblyContext_RequiredRole();

    /**
     * The meta object literal for the '<em><b>Allocation Context</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASSEMBLY_CONTEXT__ALLOCATION_CONTEXT = eINSTANCE.getAssemblyContext_AllocationContext();

    /**
     * The meta object literal for the '<em><b>Provided Role</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASSEMBLY_CONTEXT__PROVIDED_ROLE = eINSTANCE.getAssemblyContext_ProvidedRole();

    /**
     * The meta object literal for the '<em><b>Component</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASSEMBLY_CONTEXT__COMPONENT = eINSTANCE.getAssemblyContext_Component();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.LinkImpl <em>Link</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.LinkImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getLink()
     * @generated
     */
    EClass LINK = eINSTANCE.getLink();

    /**
     * The meta object literal for the '<em><b>Linked Containers</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LINK__LINKED_CONTAINERS = eINSTANCE.getLink_LinkedContainers();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.RoleImpl <em>Role</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.RoleImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getRole()
     * @generated
     */
    EClass ROLE = eINSTANCE.getRole();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.BehaviorDescriptionImpl <em>Behavior Description</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.BehaviorDescriptionImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getBehaviorDescription()
     * @generated
     */
    EClass BEHAVIOR_DESCRIPTION = eINSTANCE.getBehaviorDescription();

    /**
     * The meta object literal for the '<em><b>Called Services</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BEHAVIOR_DESCRIPTION__CALLED_SERVICES = eINSTANCE.getBehaviorDescription_CalledServices();

    /**
     * The meta object literal for the '<em><b>Internal Actions</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BEHAVIOR_DESCRIPTION__INTERNAL_ACTIONS = eINSTANCE.getBehaviorDescription_InternalActions();

    /**
     * The meta object literal for the '<em><b>Loops</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BEHAVIOR_DESCRIPTION__LOOPS = eINSTANCE.getBehaviorDescription_Loops();

    /**
     * The meta object literal for the '<em><b>Branches</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BEHAVIOR_DESCRIPTION__BRANCHES = eINSTANCE.getBehaviorDescription_Branches();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ServiceImpl <em>Service</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ServiceImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getService()
     * @generated
     */
    EClass SERVICE = eINSTANCE.getService();

    /**
     * The meta object literal for the '<em><b>Corresponding Signature</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SERVICE__CORRESPONDING_SIGNATURE = eINSTANCE.getService_CorrespondingSignature();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.InterfaceImpl <em>Interface</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.InterfaceImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getInterface()
     * @generated
     */
    EClass INTERFACE = eINSTANCE.getInterface();

    /**
     * The meta object literal for the '<em><b>Signature</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INTERFACE__SIGNATURE = eINSTANCE.getInterface_Signature();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.SignatureImpl <em>Signature</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.SignatureImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getSignature()
     * @generated
     */
    EClass SIGNATURE = eINSTANCE.getSignature();

    /**
     * The meta object literal for the '<em><b>Return Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SIGNATURE__RETURN_TYPE = eINSTANCE.getSignature_ReturnType();

    /**
     * The meta object literal for the '<em><b>Parameter Type</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SIGNATURE__PARAMETER_TYPE = eINSTANCE.getSignature_ParameterType();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.DelegationConnectorImpl <em>Delegation Connector</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.DelegationConnectorImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getDelegationConnector()
     * @generated
     */
    EClass DELEGATION_CONNECTOR = eINSTANCE.getDelegationConnector();

    /**
     * The meta object literal for the '<em><b>Role</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DELEGATION_CONNECTOR__ROLE = eINSTANCE.getDelegationConnector_Role();

    /**
     * The meta object literal for the '<em><b>Interface</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DELEGATION_CONNECTOR__INTERFACE = eINSTANCE.getDelegationConnector_Interface();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.InternalActionImpl <em>Internal Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.InternalActionImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getInternalAction()
     * @generated
     */
    EClass INTERNAL_ACTION = eINSTANCE.getInternalAction();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.LoopImpl <em>Loop</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.LoopImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getLoop()
     * @generated
     */
    EClass LOOP = eINSTANCE.getLoop();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.BranchImpl <em>Branch</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.BranchImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getBranch()
     * @generated
     */
    EClass BRANCH = eINSTANCE.getBranch();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.TypeImpl <em>Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.TypeImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getType()
     * @generated
     */
    EClass TYPE = eINSTANCE.getType();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ListImpl <em>List</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ListImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getList()
     * @generated
     */
    EClass LIST = eINSTANCE.getList();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.MapImpl <em>Map</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.MapImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getMap()
     * @generated
     */
    EClass MAP = eINSTANCE.getMap();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ComplexTypeImpl <em>Complex Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ComplexTypeImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getComplexType()
     * @generated
     */
    EClass COMPLEX_TYPE = eINSTANCE.getComplexType();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.DateImpl <em>Date</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.DateImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getDate()
     * @generated
     */
    EClass DATE = eINSTANCE.getDate();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.DoubleImpl <em>Double</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.DoubleImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getDouble()
     * @generated
     */
    EClass DOUBLE = eINSTANCE.getDouble();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.String0Impl <em>String0</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.String0Impl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getString0()
     * @generated
     */
    EClass STRING0 = eINSTANCE.getString0();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.Int0Impl <em>Int0</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.Int0Impl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getInt0()
     * @generated
     */
    EClass INT0 = eINSTANCE.getInt0();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.CharImpl <em>Char</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.CharImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getChar()
     * @generated
     */
    EClass CHAR = eINSTANCE.getChar();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.LongImpl <em>Long</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.LongImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getLong()
     * @generated
     */
    EClass LONG = eINSTANCE.getLong();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.FloatImpl <em>Float</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.FloatImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getFloat()
     * @generated
     */
    EClass FLOAT = eINSTANCE.getFloat();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.BooleanImpl <em>Boolean</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.BooleanImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getBoolean()
     * @generated
     */
    EClass BOOLEAN = eINSTANCE.getBoolean();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.VoidImpl <em>Void</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.VoidImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getVoid()
     * @generated
     */
    EClass VOID = eINSTANCE.getVoid();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.StringImpl <em>String</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.StringImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getString()
     * @generated
     */
    EClass STRING = eINSTANCE.getString();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.IntImpl <em>Int</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.IntImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getInt()
     * @generated
     */
    EClass INT = eINSTANCE.getInt();

  }

} //MyDslPackage
