/**
 * generated by Xtext 2.18.0.M3
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Service</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Service#getCorrespondingSignature <em>Corresponding Signature</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getService()
 * @model
 * @generated
 */
public interface Service extends AbstractElement
{
  /**
   * Returns the value of the '<em><b>Corresponding Signature</b></em>' reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Signature}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Corresponding Signature</em>' reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getService_CorrespondingSignature()
   * @model
   * @generated
   */
  EList<Signature> getCorrespondingSignature();

} // Service
