/**
 * generated by Xtext 2.18.0.M3
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>System</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.System#getEncapsulatedAssemblyContext <em>Encapsulated Assembly Context</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.System#getAllocationContext <em>Allocation Context</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.System#getProvidedInterfaces <em>Provided Interfaces</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.System#getEnvironment <em>Environment</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getSystem()
 * @model
 * @generated
 */
public interface System extends AbstractElement
{
  /**
   * Returns the value of the '<em><b>Encapsulated Assembly Context</b></em>' reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.AssemblyContext}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Encapsulated Assembly Context</em>' reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getSystem_EncapsulatedAssemblyContext()
   * @model
   * @generated
   */
  EList<AssemblyContext> getEncapsulatedAssemblyContext();

  /**
   * Returns the value of the '<em><b>Allocation Context</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Allocation Context</em>' reference.
   * @see #setAllocationContext(AllocationContext)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getSystem_AllocationContext()
   * @model
   * @generated
   */
  AllocationContext getAllocationContext();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.System#getAllocationContext <em>Allocation Context</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Allocation Context</em>' reference.
   * @see #getAllocationContext()
   * @generated
   */
  void setAllocationContext(AllocationContext value);

  /**
   * Returns the value of the '<em><b>Provided Interfaces</b></em>' reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Interface}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Provided Interfaces</em>' reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getSystem_ProvidedInterfaces()
   * @model
   * @generated
   */
  EList<Interface> getProvidedInterfaces();

  /**
   * Returns the value of the '<em><b>Environment</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Environment</em>' reference.
   * @see #setEnvironment(SystemEnvironment)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getSystem_Environment()
   * @model
   * @generated
   */
  SystemEnvironment getEnvironment();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.System#getEnvironment <em>Environment</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Environment</em>' reference.
   * @see #getEnvironment()
   * @generated
   */
  void setEnvironment(SystemEnvironment value);

} // System
