/**
 * generated by Xtext 2.17.0
 */
package blatt2.ide;

import blatt2.ide.AbstractBlatt2IdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class Blatt2IdeModule extends AbstractBlatt2IdeModule {
}
