/*
 * generated by Xtext 2.17.0
 */
package blatt2.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractBlatt2Validator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(EPackage.Registry.INSTANCE.getEPackage("platform:/resource/Blatt1/model/allocation.ecore#//allocation"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("platform:/resource/Blatt1/model/repository.ecore#//repository"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("platform:/resource/Blatt1/model/environment.ecore#//environment"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("platform:/resource/Blatt1/model/assembly.ecore#//assembly"));
		return result;
	}
}
