/*
 * generated by Xtext 2.17.0
 */
package blatt2.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractBlatt2ScopeProvider extends DelegatingScopeProvider {
}
