/*
 * generated by Xtext 2.17.0
 */
package blatt2.ui;

import blatt2.ui.internal.Blatt2Activator;
import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class Blatt2ExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(Blatt2Activator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		Blatt2Activator activator = Blatt2Activator.getInstance();
		return activator != null ? activator.getInjector(Blatt2Activator.BLATT2_BLATT2) : null;
	}

}
